### ISSUE TITLE
Unknown project file: "ansi"

### ISSUE THREAD

**Issue by TamaMcGlinn** [alire-project/alire#438]
This problem was introduced by commit 90959a4465 "Colorize output (#402)".
Before that, I get a different compilation error, about a horizontal tab character being illegal.
Now I get 'unknown project file: "ansi"'.

**Comment by mosteo** [comment]
This could be a case of a missing git submodule update --init --recursive` or `git pull --recurse-submodules`. Have you tried that? (In the alire repo).

**Comment by TamaMcGlinn** [comment]
Indeed; how silly of me. Thank you.
